Business understanding (CRISP-DM) ; Data understanding (CRISP-DM); Modeling (CRISP-DM)
piechart/bachelor-diploma-docs pull request #37
Opened 2020-05-03 08:40 UTC by AleksandraPavlenko

## Чеклист

- [ ] Ссылки на новые файлы добавлены в readme.md
- [ ] Добавленные файлы перечислены в названии PR

2020-05-03 18:59 UTC, piechart commented
/rebase

2020-05-03 19:01 UTC, piechart requested changes
@AleksandraPavlenko привет. Modeling и Data understanding уже есть [тут](https://github.com/piechart/bachelor-diploma-docs/blob/master/files/Dmitrieva_K3443_shablony.docx). Давай избегать дублирования

2020-05-03 19:54 UTC, AleksandraPavlenko commented
> @AleksandraPavlenko привет. Modeling и Data understanding уже есть [тут](https://github.com/piechart/bachelor-diploma-docs/blob/master/files/Dmitrieva_K3443_shablony.docx). Давай избегать дублирования

Есть) только у меня более структурированный. Если бы я искала шаблон, то обратилась бы именно к такому

2020-05-05 06:43 UTC, piechart approved these changes

2020-05-05 06:43 UTC, merged